<?php

declare(strict_types=1);

/**
 * Auto-loads the crabmagick native PHP extension from the bundled binary.
 *
 * This file is registered in composer.json autoload.files and runs
 * automatically on every `require vendor/autoload.php`.
 *
 * The extension is activated via PHP_INI_SCAN_DIR — no system php.ini
 * changes or sudo required. After `composer install`, run PHP with:
 *
 *   PHP_INI_SCAN_DIR=:/path/to/vendor/usernamn0tavailable/crabmagick php ...
 *
 * The Composer post-install hook generates crabmagick.ini in that directory
 * with the correct absolute extension path.
 *
 * If the extension is already loaded (via php.ini or the scan-dir approach),
 * this file is a no-op. If it isn't, it logs a helpful hint.
 */
(static function (): void {
    if (extension_loaded('crabmagick-php')) {
        return;
    }

    // Try dl() in case the host has enable_dl=On.
    $phpVer = PHP_MAJOR_VERSION . '.' . PHP_MINOR_VERSION;
    $arch   = php_uname('m');
    $so     = __DIR__ . '/../ext/crabmagick-php' . $phpVer . '-' . $arch . '-linux.so';

    if (file_exists($so) && function_exists('dl') && ini_get('enable_dl')) {
        dl($so);
        return;
    }

    // Emit a notice with the exact PHP_INI_SCAN_DIR command to use.
    $dir = realpath(__DIR__ . '/..') ?: __DIR__ . '/..';
    trigger_error(
        "[crabmagick] Extension not loaded. Start PHP with:\n"
        . "  PHP_INI_SCAN_DIR=:{$dir} php ...\n"
        . "(crabmagick.ini in that directory is generated by `composer install`)",
        E_USER_NOTICE
    );
})();
