<?php

declare(strict_types=1);

/**
 * Auto-loads the crabmagick native PHP extension from the bundled binary.
 *
 * Registered in composer.json autoload.files — runs on every
 * `require vendor/autoload.php`. No-op if already loaded.
 *
 * Variant selection (same logic as Installer.php):
 *   1. Auto-detect CPU features (AVX-512 / AVX2 / SVE)
 *   2. Fall back to generic arch binary
 *
 * If dl() is available and enable_dl=On, loads directly.
 * Otherwise emits a notice pointing to PHP_INI_SCAN_DIR.
 */
(static function (): void {
    if (extension_loaded('crabmagick-php')) {
        return;
    }

    $phpVer = PHP_MAJOR_VERSION . '.' . PHP_MINOR_VERSION;
    $arch   = php_uname('m');
    $extDir = __DIR__ . '/../ext';

    $so = self_crabmagick_resolve($extDir, $phpVer, $arch);
    if ($so === null) {
        return;
    }

    if (function_exists('dl') && ini_get('enable_dl')) {
        dl($so);
        return;
    }

    $dir = realpath(__DIR__ . '/..') ?: __DIR__ . '/..';
    trigger_error(
        "[crabmagick] Extension not loaded. Start PHP with:\n"
        . "  PHP_INI_SCAN_DIR=:{$dir} php ...\n"
        . "(crabmagick.ini is generated by `composer install` with the correct path)",
        E_USER_NOTICE
    );
})();

function self_crabmagick_resolve(string $extDir, string $phpVer, string $arch): ?string
{
    $variant = self_crabmagick_detect_variant($arch);
    $candidates = array_unique(array_filter([$variant, $arch]));
    foreach ($candidates as $v) {
        $path = $extDir . "/crabmagick-php{$phpVer}-{$v}-linux.so";
        if (file_exists($path)) {
            return $path;
        }
    }
    return null;
}

function self_crabmagick_detect_variant(string $arch): ?string
{
    if ($arch === 'x86_64') {
        $cpuinfo = @file_get_contents('/proc/cpuinfo') ?: '';
        if (preg_match('/\bflags\b.*\bavx512f\b/m', $cpuinfo)) {
            return 'x86_64-avx512';
        }
        if (preg_match('/\bflags\b.*\bavx2\b/m', $cpuinfo)) {
            return 'x86_64-avx2';
        }
        return null;
    }

    if ($arch === 'aarch64' || $arch === 'arm64') {
        $cpuinfo = @file_get_contents('/proc/cpuinfo') ?: '';
        if (preg_match('/\bFeatures\b.*\bsve\b/mi', $cpuinfo)) {
            return 'aarch64-sve';
        }
        return null;
    }

    return null;
}
